### ISSUE TITLE
[Mysql & GUI] Authentication process is only staring when written email exist in the database  

### ISSUE THREAD

**Issue by emanuelkrzyszton** [davidgmorais/mais#8]
During process of authentication in the window when the user have to writte down his email if the written email is not existing in the database the next window should appear with information 'Something went wrong try again.' with three buttons register, home and cancel.

**Comment by davidgmorais** [comment]
Only the email validity is verified when the user writes it downs. Even if the user does not exist, the face authentication proceeds in order to make it impossible to see which emails are currently stored in the database.
